<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="0.183" timestamp="2024-04-03T20:54:52.526823" hostname="DESKTOP-4IAF3OU"><testcase classname="" name="tests.test_bytebank" time="0.000"><error message="collection failure">ImportError while importing test module 'C:\Users\Gustavo\Desktop\GitHub\Python\Python_e_TDD\tests\test_bytebank.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\..\..\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests\test_bytebank.py:1: in &lt;module&gt;
    from Python_e_TDD.codigo.bytebank import Funcionario
E   ModuleNotFoundError: No module named 'Python_e_TDD'</error></testcase></testsuite></testsuites>